### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ciB89** [rytilahti/homeassistant-upnp-availability#1]
I tried using your integration, but after installing it via HACS and restarting, I cannot find it in the integrations when adding it.

Using HACS 1.11.3 and core-2021.3.3

**Comment by brgerig** [comment]
I had the same problem, but it turned out the github was down, so HACS couldn't get the code. I'd say try installing it in HACS again and see if it's there.

**Comment by ciB89** [comment]
> I had the same problem, but it turned out that github was down as far as downloading code, so HACS couldn't get the code. I'd say try installing it in HACS again and see if it's there.

Thanks, it works now :)

**Comment by rytilahti** [comment]
Glad to hear you got it working! Otherwise I would have thought that it has something to do with what interfaces are being listened on on multi-network systems (I have never tried this in hass/docker).
