### ISSUE TITLE
Error after upgrade to HA 2022.11.1

### ISSUE THREAD

**Issue by crackalak** [rytilahti/homeassistant-upnp-availability#12]
```
Logger: homeassistant.components.binary_sensor
Source: custom_components/upnp_availability/upnpstatustracker.py:215
Integration: Binary Sensor (documentation, issues)
First occurred: 19:02:31 (1 occurrences)
Last logged: 19:02:31

Error while setting up upnp_availability platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/upnp_availability/binary_sensor.py", line 51, in async_setup_entry
    await tracker.find_devices()
  File "/config/custom_components/upnp_availability/upnpstatustracker.py", line 211, in find_devices
    await self._search(source_address, async_callback)
  File "/config/custom_components/upnp_availability/upnpstatustracker.py", line 215, in _search
    await async_search(
TypeError: async_search() got an unexpected keyword argument 'service_type'
```

**Comment by crackalak** [comment]
Looks to actually be due to [https://github.com/StevenLooman/async_upnp_client/pull/144/files](https://github.com/StevenLooman/async_upnp_client/pull/144/files) 
Released in async_upnp_client 0.32.0

**Comment by rytilahti** [comment]
Hi Dan and thanks for the report! I cannot currently test this myself, but would you mind checking if the linked PR works for you?

**Comment by crackalak** [comment]
@rytilahti I wasn't sure how to download from a branch within hacs so applied the change manually, it's working now thanks! 😀

Though I notice that it has created an additional sensor for home assistant itself:
![Screenshot_20221103-211238](https://user-images.githubusercontent.com/4701936/199835269-ec77016d-379a-4fe0-a16b-b04cb056ab93.png)

**Comment by rytilahti** [comment]
Yeah, the some recent homeassistant release started to advertise itself (again?). Maybe that's causing it? You could check what attributes it does expose to see if that's the case.

**Comment by crackalak** [comment]
@rytilahti yea that seems to be the case
