### ISSUE TITLE
No associated image for integration

### ISSUE THREAD

**Issue by ScottG489** [rytilahti/homeassistant-upnp-availability#17]
There doesn't seem to be an image for this integration. This would be nice to have on the integration page itself:

<img width="250" alt="Screen Shot 2022-12-02 at 1 04 33 PM" src="https://i.imgur.com/eSZWmkt.png">

and also on the list of devices for this integration:
<img width="250" alt="Screen Shot 2022-12-02 at 1 04 33 PM" src="https://i.imgur.com/8nN0qm2.png">

**Comment by rytilahti** [comment]
Getting the icon fixed on the integration page would require creating a PR to the brands repository or finding out a way how the already existing "upnp" brand could be used for custom components.

The linked PR will add a device-provided icon to show in parts of homeassistant, looks like that was enough to hide those broken images shown in your second screenshot :-)

**Comment by ScottG489** [comment]
Hey thanks for making those changes! Unfortunately it seems like on the device page I'm still seeing the same missing image icons as seen in my second picture above.

**Comment by rytilahti** [comment]
Ah, I'm not sure if that page really uses the `entity_picture`... I think this integration should be converted to expose the sensors per-device basis (currently it's just binary_sensors for each and every device and "subdevice" a device offers), maybe that would fix it.

However, the linked branding PR is still open, which would fix the icons in the list when it gets merged.

**Comment by ScottG489** [comment]
Btw it looks like the images are showing up on the device page now! Thanks so much for getting this worked out.

I'm happy with closing this, but I'll leave that up to you in case there's any residual work that needs to be finished that I'm unaware of!
