### ISSUE TITLE
HA Integration Not Working 

### ISSUE THREAD

**Issue by smartypants1138** [rytilahti/homeassistant-upnp-availability#20]
Xbox power events are not triggering in HA

**Comment by rytilahti** [comment]
Thanks for reporting @smartypants1138, this should be now fixed!

**Comment by smartypants1138** [comment]
Thank you for the fix and for all your work on this integration! I sent you a sponsorship, I love your UPnP Availability integration, keep up the great work!

Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by rytilahti** [comment]
Glad to hear it's working for you and thank you very much! It's always heartwarming to hear that there are people out there who find my software useful! :-)
