### ISSUE TITLE
Unable to fetch device info for Device

### ISSUE THREAD

**Issue by tjorim** [rytilahti/homeassistant-upnp-availability#24]
```
Unable to fetch device info for Device(udn='uuid:xxxxxxxx-xxxx-xxxx-xxxx-412bdd8b9f5f', url='http://192.168.1.103:8008/ssdp/device-desc.xml', last_update=datetime.datetime(2023, 2, 24, 16, 34, 18, 216283), alive=False, name=None, max_age=1800, info={}): Did not receive HTTP 200 but 404
Unable to fetch device info for Device(udn='uuid:yyyyyyyy-yyyy-yyyy-yyyy-3eb1d6c67d81', url='http://192.168.1.1:1990/ad79a3dd-e005-4dba-a8ba-200ad8bc3bd4/WFADevice.xml', last_update=datetime.datetime(2023, 2, 24, 16, 34, 18, 216283), alive=False, name=None, max_age=600, info={}): ('TimeoutError()', None)
```

**Comment by rytilahti** [comment]
This is (sometimes) normal and can happen if the device does not respond in the url given in the advertisement. I think it should not affect the basic use besides no icons are shown properly.

**Comment by tjorim** [comment]
Can this error not get catched?

**Comment by rytilahti** [comment]
@tjorim I'm not sure what you mean by catching, but the linked PR marks the device now as available (and logs a warning instead of an error) when fetching fails. Would that work for you?

**Comment by rytilahti** [comment]
This should be fixed by the linked PR that has already been merged. Please reopen and provide more information, if you are still having the issue.
