### ISSUE TITLE
Xbox Sensing 

### ISSUE THREAD

**Issue by smartypants1138** [rytilahti/homeassistant-upnp-availability#26]
Hello - the UPnP availability sensor isn't picking up Xbox events. 

Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3
Frontend 20230608.0 - latest

**Comment by smartypants1138** [comment]
False alarm, all is well!

**Comment by rytilahti** [comment]
I was wondering if a newer async_upnp_client version could have broken it, but glad to hear that it was a false alarm!

[the cli tool](https://github.com/rytilahti/homeassistant-upnp-availability#testing-the-discovery-without-homeassistant) can be helpful for tracking issues.
