### ISSUE TITLE
No version key in manifest file

### ISSUE THREAD

**Issue by brgerig** [rytilahti/homeassistant-upnp-availability#3]
On Home Assistant start, core-2021.3.2:

`2021-03-12 14:51:19 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'upnp_availability'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'upnp_availability'
`

**Comment by rytilahti** [comment]
Oops, I accidentally pushed to master instead of using a separate branch and PR. Anyway, this should now be fixed with https://github.com/rytilahti/homeassistant-upnp-availability/commit/fc136939df8daedfa09990779003ab2bc1edf1c8 – thanks for reporting!
