### ISSUE TITLE
uPNP issue - sensors not updating

### ISSUE THREAD

**Issue by HermesHonshappo** [rytilahti/homeassistant-upnp-availability#30]
Can't really explain when it happened, but the uPNP sensor couldn't detect my xbox reliably anymore

Example below. The first 2 sensors are generated by node-red, and show that xbox is currently running Starfield. last 2 sensors have been created by the upnp availability integration, but do not update anymore
![image](https://github.com/user-attachments/assets/e03c9121-4288-4be1-a567-9673769f9a96)

I erased completely the integration, and added it back. When the xbox is started the first time, the upnp sensors are created and set to "on". Then when the xbox turns off, the sensors switch to "off", and never turn back on

It seems to be correlated with the exclusion of "media_player.*" sensors from history in configuration.yaml
```history:
  exclude:
    domains:
      - automation
      - updater
    entity_globs:
      - update.*
      - binary_sensor*_update_available
      - media_player.*                  #remove stats for media_players
```

~~When I enable this back in history settings, and after a reboot of HA, the uPNP sensors are now detecting the upnp players again~~

~~I'm not sure if this is normal or not.  I don't see the use to keep an history of the media-player entities, but will do so for now.~~

EDIT: even after re-enabling the setting in config.yaml, the update of upnp sensors doesn't seem to work.
Turning on then off an xbox, or a netradio does not update the binary_sensor. The upnp sensors are only updated when HA reboots.

I have the latest version of HAOS, running in a proxmox VM. Not sure when kind of debug or logs I could share to help troubleshoot.

EDIT2: Nope, after a while, uPNP availability sensors stop updating. I am now in a state where I can turn xbox, or plex server, or netradio off and on but upnp availability sensors remain stuck in "off" status.

![image](https://github.com/user-attachments/assets/a54850a1-248e-4303-a1ae-b75cdf2afa14)

**Comment by HermesHonshappo** [comment]
No recent change on the LAN. I tried turning off avahi on the pfsense router, but I doubt it would be related.
If that doesn't work I'll try enabling debug logs.

**Comment by rytilahti** [comment]
So UPnP uses something called SSDP in the background. SSDP uses multicast for delivering notifications, so if the host is unable to join the correct multicast group, it won't get the notifications at all. I don't know the in-depth details, but perhaps your switch filters multicast traffic instead of delivering it on all ports, while with [IGMP snooping](https://en.wikipedia.org/wiki/IGMP_snooping) enabled it forwards them as expected?
