### ISSUE TITLE
Google Streamer 4K

### ISSUE THREAD

**Issue by Yumanbeing** [rytilahti/homeassistant-upnp-availability#33]
I get lots of errors saying “ Got bye from unknown device:” ever since getting the Streamer. 

I even uninstalled the integration, rebooted, reinstalled the integration and disabled “enable newly added entities” and “enable polling for updates”, plus tried every combination of those two settings I could. 

So, the streamer never appears in the availability integration at all, but it keeps giving me the error.

**Comment by rytilahti** [comment]
Hey, sorry to hear that, I just created a PR that fixes this by hiding that type of log entries from the error log.
If you need to track the status of this device, we will need to debug it a bit more to see why that's the case. Let me know if you wish to provide logs to help with that!

edit: Added the necessary loggers to the manifest in #35, so you can use the "enable debug logging" button directly from homeassistant to enable logging. You could enable it and check if there is non-bye traffic from the device at all.
