### ISSUE TITLE
Setting a connection_class has been deprecated

### ISSUE THREAD

**Issue by deadly667** [rytilahti/homeassistant-upnp-availability#4]
Hi,
after update Home Assistant to 2021.6 I saw this warning log:

"The UPnP Availability (upnp_availability) integration is setting a connection_class when calling the 'register_discovery_flow()' method in its config flow. The connection class has been deprecated and will be removed in a future release of Home Assistant. If 'upnp_availability' is a custom integration, please contact the author of that integration about this warning."

Thanks

**Comment by rytilahti** [comment]
Hi and thanks for the report! If you want & know what needs to be changed, feel free to open a PR to adapt the code to use the expected format. Otherwise, I'll try to take a look into fixing it in the near future (in a couple of weeks).

**Comment by deadly667** [comment]
And I did it :)

https://github.com/rytilahti/homeassistant-upnp-availability/pull/5
